# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
# Journeys は構成キャッシュ有効時に、別の Journey が実行される・認証エラーになるといった
# 既知の問題がある。https://developer.android.com/studio/gemini/journeys#known-issues
org.gradle.configuration-cache=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
